### ISSUE TITLE
The architecture doesn't work

### ISSUE THREAD

**Issue by tombinic** [hyunnamlee/RAPUNet#1]
Hi! I was trying to replicate your architecture but it gave me the following error:

ValueError: Input 0 of layer "conv2d_3" is incompatible with the layer: expected min_ndim=4, found ndim=3. Full shape received: (None, 484, 320)

I'm using tf v.2.10.0.

**Comment by hyunnamlee** [comment]
Hello.
Actually, I don’t see such error when I work with my code.  I checked whole my code, but I don’t find any clue until now. 
I’ll try to check my code and I find any clue, let you know. Have a great day.

**Comment by tombinic** [comment]
Thank you for the reply. Which version of TensorFlow/Keras are you using?
Thanks.

**Comment by hyunnamlee** [comment]
I used Tensorflow v2.13.0, but  I don’t remember Keras version.   Unfortunately, the workstation I used for this work is not here. I hope it’ll help you!!


I think your error is from input data (images).  Usually input of Network is 4 dim  ( ex. ( # of batch, 3, width, height) ).  please check the image and mask path or image loading part or imput image size…

**Comment by LuzianU** [comment]
fixed by installing `keras_cv_attention_models==1.3.9`

**Comment by hyunnamlee** [comment]
Thank yo LuzianU ..

I updated “Implementation Enviroments” in README
